const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const chessRoutes = require('./routes/chess');
const errorHandler = require('./middleware/errorHandler');
const fs = require('fs');
const path = require('path');

const app = express();
// Port tidak lagi digunakan di Vercel, tapi bisa disimpan untuk testing lokal
const port = process.env.PORT || 3000;

// Middleware untuk mem-parsing body request JSON
app.use(express.json());

// Endpoint utama untuk mendapatkan langkah terbaik
app.post('/api/get-best-move', async (req, res) => {
    const { fen, depth, movetime } = req.body;

        // Validasi input: FEN string wajib ada
            if (!fen) {
                    return res.status(400).json({
                                success: false,
                                            error: 'FEN string is required in the request body.'
                                                    });
                                                        }

                                                            // Tentukan parameter pencarian, prioritaskan movetime jika ada
                                                                const searchParam = movetime ? `movetime ${movetime}` : `depth ${depth || 15}`;

                                                                    let engine;
                                                                        try {
                                                                                // Gunakan dynamic import untuk memuat package stockfish (kompatibel dengan modul modern)
                                                                                        const stockfishModule = await import('stockfish');
                                                                                                const stockfish = stockfishModule.default;

                                                                                                        // Inisialisasi instance engine Stockfish baru untuk setiap request.
                                                                                                                engine = await stockfish();

                                                                                                                        let bestMove = '';
                                                                                                                                let lastInfo = '';

                                                                                                                                        // Gunakan Promise untuk menunggu respons 'bestmove' dari engine
                                                                                                                                                const analysisPromise = new Promise((resolve, reject) => {
                                                                                                                                                            // Listener untuk pesan dari engine
                                                                                                                                                                        engine.onmessage = (message) => {
                                                                                                                                                                                        console.log(`Engine: ${message}`); // Log untuk debugging (akan muncul di Vercel Logs)

                                                                                                                                                                                                        if (typeof message !== 'string') return;

                                                                                                                                                                                                                        // Simpan info terakhir (termasuk evaluasi skor)
                                                                                                                                                                                                                                        if (message.startsWith('info')) {
                                                                                                                                                                                                                                                            lastInfo = message;
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            // Jika engine sudah menemukan langkah terbaik, selesaikan Promise
                                                                                                                                                                                                                                                                                                            if (message.startsWith('bestmove')) {
                                                                                                                                                                                                                                                                                                                                const parts = message.split(' ');
                                                                                                                                                                                                                                                                                                                                                    bestMove = {
                                                                                                                                                                                                                                                                                                                                                                            move: parts[1],
                                                                                                                                                                                                                                                                                                                                                                                                    ponder: parts[3] || null // Langkah 'ponder' (prediksi balasan lawan)
                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                            resolve();
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Atur timeout untuk mencegah request menggantung terlalu lama
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Vercel Hobby plan memiliki timeout maksimal sekitar 10-15 detik.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reject(new Error('Engine analysis timed out.'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 10000); // Timeout 10 detik, aman untuk Vercel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Kirim perintah UCI ke engine
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await engine.uci();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        engine.postMessage(`position fen ${fen}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                engine.postMessage(`go ${searchParam}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Tunggu hingga analisis selesai
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await analysisPromise;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Atur header cache untuk performa yang lebih baik di Vercel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.setHeader('Cache-Control', 's-maxage=1, stale-while-revalidate');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    search: searchParam,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bestMove: bestMove.move,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ponder: bestMove.ponder,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        info: lastInfo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Error during Stockfish analysis:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error: error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Pastikan untuk menghentikan proses engine setelah selesai
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (engine) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    engine.postMessage('quit');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Penambahan endpoint root sederhana untuk verifikasi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.get('/api', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(200).send('Stockfish API is running. Use POST /api/get-best-move to get an analysis.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Ekspor app untuk Vercel agar bisa dijalankan sebagai Serverless Function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = app;
